<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy-Assignment" data-toc-modified-id="Numpy-Assignment-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy Assignment</a></span><ul class="toc-item"><li><span><a href="#Housing-Arrays" data-toc-modified-id="Housing-Arrays-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Housing Arrays</a></span></li><li><span><a href="#Housing-Features" data-toc-modified-id="Housing-Features-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Housing Features</a></span></li><li><span><a href="#Array-Shape" data-toc-modified-id="Array-Shape-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Array Shape</a></span></li><li><span><a href="#Load-Dataset" data-toc-modified-id="Load-Dataset-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Load Dataset</a></span></li><li><span><a href="#Slice" data-toc-modified-id="Slice-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Slice</a></span></li><li><span><a href="#Conditional-Subsetting" data-toc-modified-id="Conditional-Subsetting-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Conditional Subsetting</a></span></li><li><span><a href="#Row-/-Value-Replacement" data-toc-modified-id="Row-/-Value-Replacement-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Row / Value Replacement</a></span></li><li><span><a href="#Save-Array-To-File" data-toc-modified-id="Save-Array-To-File-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Save Array To File</a></span></li><li><span><a href="#Load-.csv-File" data-toc-modified-id="Load-.csv-File-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Load .csv File</a></span></li><li><span><a href="#Display-Column-Mean" data-toc-modified-id="Display-Column-Mean-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Display Column Mean</a></span></li><li><span><a href="#Subtract-Values-From-Array-Columns" data-toc-modified-id="Subtract-Values-From-Array-Columns-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Subtract Values From Array Columns</a></span></li><li><span><a href="#Multiply-Each-Element-By-2" data-toc-modified-id="Multiply-Each-Element-By-2-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Multiply Each Element By 2</a></span></li></ul></li></ul></div>

To:&nbsp;&nbsp;&nbsp;&nbsp; Magnimind

From: Matt Curcio, matt.curcio.ri@gmail.com

Date: 2022-10-01

Re:&nbsp;&nbsp;&nbsp; Intro. to Python

## Numpy Assignment

### Housing Arrays
Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.


In [1]:
from __future__ import print_function, division
import numpy as np

from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; } </style>"))

In [2]:
sq_m = [x*100 for x in range(1, 11)]
print('SQ_M = ', sq_m, '\n')
rooms = [x+1 for x in range(1, 11)]
print('Rooms = ', rooms, '\n')
list_price = [x*50000 for x in range(1, 11)]
print('List Price = ', list_price)

SQ_M =  [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] 

Rooms =  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11] 

List Price =  [50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000, 450000, 500000]


In [3]:
arr_sq_m = np.array(sq_m)
arr_rooms = np.array(rooms)
arr_list_price = np.array(list_price)

housing = np.vstack((arr_sq_m, arr_rooms, arr_list_price))

print(housing)

[[   100    200    300    400    500    600    700    800    900   1000]
 [     2      3      4      5      6      7      8      9     10     11]
 [ 50000 100000 150000 200000 250000 300000 350000 400000 450000 500000]]


### Housing Features
Transpose the array you have created, so that every line can represent features of one house.

In [4]:
units = housing.transpose()
units

array([[   100,      2,  50000],
       [   200,      3, 100000],
       [   300,      4, 150000],
       [   400,      5, 200000],
       [   500,      6, 250000],
       [   600,      7, 300000],
       [   700,      8, 350000],
       [   800,      9, 400000],
       [   900,     10, 450000],
       [  1000,     11, 500000]])

### Array Shape
Display the shape of the array and explain what it means.

In [5]:
units.shape

(10, 3)

In [6]:
!pwd
!ls

/home/mcc/Dropbox/9-Magni-mind/7_Numpy_Assignment
'2022-10-11 Numpy Assignment.beta.ipynb'
'2022-10-11 Numpy Assignment.ipynb'
'2022-10-11 Read .csv file.ipynb'
'2022-10-12 NumPy Basics.ipynb'
 earthquakes1970-2014.csv
 numpy_assignment_questions.txt
 sub_set.csv
'testing numpy find index of row x>y.ipynb'


### Load Dataset
Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [7]:
import numpy as np

filename = 'earthquakes1970-2014.csv'
data_array = np.genfromtxt(filename, delimiter=",", skip_header=1)
data_array[0:2]

array([[            nan,  2.41390000e+01,  1.02503000e+02,
         3.10000000e+01,  7.50000000e+00,             nan,
         9.00000000e+01,             nan,             nan,
         0.00000000e+00,             nan,  1.97001044e+09],
       [            nan, -9.62800000e+00,  1.51458000e+02,
         8.00000000e+00,  6.20000000e+00,             nan,
         8.50000000e+01,             nan,             nan,
         0.00000000e+00,             nan,  1.97001064e+09]])

In [8]:
data_array.shape

(5304, 12)

### Slice
Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [9]:
# Note to self: Numpy <- (rows, columns)

sub_set = data_array[0:20, (2, 4, 5, 6, 11)]

sub_set.shape

(20, 5)

In [10]:
sub_set[0:1, :]

array([[1.02503000e+02, 7.50000000e+00,            nan, 9.00000000e+01,
        1.97001044e+09]])

### Conditional Subsetting
Display the row numbers where last values are equal to 4.5 or higher.  
AKA: **numpy select elements by condition**

In [11]:
# Get INDEX of values greater than 10
arr_gte_45 = np.asarray(sub_set[:, -1] >= 4.5).nonzero()
arr_gte_45

(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 15, 16, 17, 19]),)

In [12]:
sub_set[:, -1]

array([1.97001044e+09, 1.97001064e+09, 1.97001084e+09, 1.97001104e+09,
                  nan, 1.97001204e+09, 1.97001204e+09, 1.97001214e+09,
       1.97001264e+09, 1.97002044e+09, 1.97002054e+09, 1.97002064e+09,
       1.97002244e+09,            nan,            nan, 1.97003044e+09,
       1.97003094e+09, 1.97003104e+09,            nan, 1.97003154e+09])

### Row / Value Replacement
Assign 1 to first row.

**This question is puzzling to me**. To **sub-set or original**.   

In [13]:
sub_set[0, :] = 1

In [14]:
sub_set[0:2, :]

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00],
       [1.51458000e+02, 6.20000000e+00,            nan, 8.50000000e+01,
        1.97001064e+09]])

### Save Array To File
Save the final state of the array to disk. You are going to use this in the next assignment.

In [15]:
np.savetxt('sub_set.csv', sub_set, delimiter=',')

### Load .csv File
Load the array you saved in the previous lesson from the disk.

In [16]:
sub_set = np.loadtxt('sub_set.csv', delimiter=',')
sub_set.shape

(20, 5)

### Display Column Mean
Display the mean and the standard deviation for each column.

In [17]:
# This produces the mean showing 'nan' in columns.

print('Column means: ', np.mean(sub_set, axis=0))
print('Standard Deviation means:', np.std(sub_set, axis=0))

Column means:  [22.11561  5.99         nan 75.6          nan]
Standard Deviation means: [138.40363531   1.16528966          nan  55.81343924          nan]


In [18]:
# This produces the mean IGNORING 'nan' in columns.

print('Column means: ', np.nanmean(sub_set, axis=0))
print('Standard Deviation means:', np.nanstd(sub_set, axis=0))

Column means:  [2.21156100e+01 5.99000000e+00 1.00000000e+00 7.56000000e+01
 1.84689309e+09]
Standard Deviation means: [1.38403635e+02 1.16528966e+00 0.00000000e+00 5.58134392e+01
 4.76865744e+08]


### Subtract Values From Array Columns
Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be done in one line of code.)

In [19]:
## Column 1, SUBTRACT 1
arr_1 = np.ones(20)
sub_set[:,0]

np.subtract(sub_set[:,0], arr_1)

array([   0.    ,  150.458 ,  177.568 ,  125.737 , -153.66  , -178.349 ,
        141.966 , -105.298 ,  165.37  , -100.484 ,  121.117 ,   99.775 ,
        102.031 , -180.5898, -176.04  ,  142.707 ,  167.603 ,  147.87  ,
       -154.97  ,  -70.499 ])

In [20]:
## Column 2, SUBTRACT 25
arr_25 = np.ones(20) * 25
#sub_set[:,1]

np.subtract(sub_set[:,1], arr_25)

array([-24. , -18.8, -18.9, -18.9, -19. , -18.5, -18.6, -18.4, -18.6,
       -18.5, -18.4, -18.9, -19. , -19. , -18.9, -18.8, -18.5, -19. ,
       -18.5, -19. ])

In [21]:
## Column 3, SUBTRACT 25
np.subtract(sub_set[:,2], arr_25)

array([-24.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])

In [22]:
## Column 4, SUBTRACT 10
arr_10 = np.ones(20) * 10
sub_set[:,3]

np.subtract(sub_set[:,3], arr_10)

array([ -9.,  75.,  49.,  81., -10., 165., 189., 130.,  81.,  90.,  84.,
        47.,  84., -10., -10.,  72.,  51.,  55., -10., 108.])

In [23]:
## Column 5, SUBTRACT 4
arr_4 = np.ones(20) * 4
sub_set[:,4]

np.subtract(sub_set[:,4], arr_4)

array([-3.00000000e+00,  1.97001064e+09,  1.97001084e+09,  1.97001104e+09,
                   nan,  1.97001204e+09,  1.97001204e+09,  1.97001214e+09,
        1.97001264e+09,  1.97002044e+09,  1.97002054e+09,  1.97002064e+09,
        1.97002244e+09,             nan,             nan,  1.97003044e+09,
        1.97003094e+09,  1.97003104e+09,             nan,  1.97003154e+09])

### Multiply Each Element By 2
Multiply each element by 2. (Remember it can be done in one line of code.)

In [24]:
new_matrix = np.multiply(sub_set,2)

new_matrix[:2] # displays only first 2 rows, like `.head`

array([[2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
        2.00000000e+00],
       [3.02916000e+02, 1.24000000e+01,            nan, 1.70000000e+02,
        3.94002128e+09]])